### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by manutenfruits**
I ran `npm test` and everything passed. Let me know if I need to do anything wrt releases.

### CODE REVIEW

**Comment by dozoisch** [comment]
Awesome :)! Hmm I think with babel you need to add https://babeljs.io/docs/usage/cli/ babel-cli also!

**Comment by manutenfruits** [comment]
Ha, that's funny. Since I had read [this blog post](https://babeljs.io/blog/2015/10/31/setting-up-babel-6) a few months ago, I though `babel-cli` was meant to be run globally. Turns out it's the opposite. I'll add another commit in a sec

**Comment by dozoisch** [comment]
Looks good! I'll merge it & publish when I get 2 mins today :)

**Comment by manutenfruits** [comment]
Awesome! Thanks!

**Comment by dozoisch** [comment]
merged https://github.com/eslint-plugins/eslint-plugin-lean-imports/commit/b2cc0aed5d166ddc009652242621a0bb11974de2 (closing the pr ! cause github didn't auto close it)

**Pull request closed without merging**
